package com.example.aitravelplanner.data.repository.travel

import com.example.aitravelplanner.data.model.Stage
import com.example.aitravelplanner.data.model.Travel
import com.example.aitravelplanner.data.model.User

interface ITravelRepository {
    // Add a travel in the Firestore database, under "travels" collection
    suspend fun setTravel(travel: Travel)
    // Add a stage to a specific travel (update the stages list of a travel)
    suspend fun setStageByTravel(idTravel: String, stage: Stage)
    // When a user shares his/her travel, the the boolean travel's variable "isShared" is set to true
    suspend fun setTravelToShared(idTravel: String)
    // Get all the travels in the Firestore database
    suspend fun getSharedTravels(idUser: String): ArrayList<Travel>
    // Get a travel with a specific idTravel as a string
    suspend fun getTravelById(idTravel: String, idUser: String): Travel?
    // Get all the travel's stages
    suspend fun getStagesByTravel(idTravel: String): ArrayList<Stage>
    // Get the travel created/generated by a given user
    suspend fun getTravelsCreatedByUser(user: User): ArrayList<Travel>
}